name: Move

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
        with:
          fetch-depth: 1

      - name: Install Sui
        uses: cloudposse-github-actions/install-gh-releases@5a4dcf2f959d64832a8e2fe3e8063e4adac6af88 # pin@v1.4.1
        with:
          config: |-
            mystenlabs/sui:
              platform: ubuntu
              arch: x86_64
              extension-matching: true
              tag: testnet-v1.52.1

      - name: Run move tests
        run: |
          for dir in move/*; do
            echo "Running sui move test in $dir"
            sui move test --path $dir
          done
